--
-- require("noice").setup({
--     views = {
--         cmdline_popup = {
--             position = {
--                 row = 5,
--                 col = "50%",
--             },
--             size = {
--                 width = 60,
--                 height = "auto",
--             },
--         },
--         popupmenu = {
--             relative = "editor",
--             position = {
--                 row = 8,
--                 col = "50%",
--             },
--             size = {
--                 width = 60,
--                 height = 10,
--             },
--             border = {
--                 style = "rounded",
--                 padding = { 0, 1 },
--             },
--             win_options = {
--                 winhighlight = { Normal = "Normal", FloatBorder = "DiagnosticInfo" },
--             },
--         },
--     },
--     messages = {
--         -- NOTE: If you enable messages, then the cmdline is enabled automatically.
--         -- This is a current Neovim limitation.
--         enabled = true, -- enables the Noice messages UI
--         view = "mini", -- default view for messages
--         view_error = "notify", -- view for errors
--         view_warn = "notify", -- view for warnings
--         view_history = "messages", -- view for :messages
--         view_search = "virtualtext", -- view for search count messages. Set to `false` to disable
--     },
-- })
